const actionTypes = {
	ADD_TODO: 'ADD_TODO',
	DELETE_TODO: 'DELETE_TODO',
	SELECT_TODO: 'SELECT_TODO',
	EDIT_TODO: 'EDIT_TODO',
	SELECT_ALL_TODO: 'SELECT_ALL_TODO',
	DELETE_COMPLETED_TODO: 'DELETE_COMPLETED_TODO',
	ALL_COMPLETED_CHANGE: 'ALL_COMPLETED_CHANGE',
	FILTER_CHANGE: 'FILTER_CHANGE',
};

const {
	ADD_TODO,
	DELETE_TODO,
	SELECT_TODO,
	EDIT_TODO,
	SELECT_ALL_TODO,
	DELETE_COMPLETED_TODO,
	FILTER_CHANGE,
	ALL_COMPLETED_CHANGE,
} = actionTypes;

export {
	ADD_TODO,
	DELETE_TODO,
	SELECT_TODO,
	EDIT_TODO,
	SELECT_ALL_TODO,
	DELETE_COMPLETED_TODO,
	FILTER_CHANGE,
	ALL_COMPLETED_CHANGE,
};
