export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const SELECT_TODO = 'SELECT_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const SELECT_ALL_TODO = 'SELECT_ALL_TODO';
export const DELETE_COMPLETED_TODO = 'DELETE_COMPLETED_TODO';
export const ALL_COMPLETED_CHANGE = 'ALL_COMPLETED_CHANGE';
export const FILTER_CHANGE = 'FILTER_CHANGE';
